### ISSUE TITLE
No defined phonology for 'r', accented/condensed letters, '

### ISSUE THREAD

**Issue by nfd9001** [XXIIVV/vessel.lietal#1]
I assume 'r' to be a "whatever-rhotic" (though I don't assert that this is a _best_ choice, especially if this is intended to be an auxlang; eg. it'd be harder for native Japanese speakers to pronounce). There's also no defined way to pronounce adultspeak condensed vowels (simple emphasis or stress doesn't seem sufficient, especially where we're doubling-up on one syllable. eg. darokiki vs. darokï). I'd also assume the ' glyph indicates a pause, but it may be a good idea to state this explicitly. 'p' appears to currently be unused.

Consider specifying the phonology against IPA.

**Comment by neauoire** [comment]
Oh! Thank you. Good catch, the phonology section is sort of an artefact of the older version. I will freshen this up a bit this week :)

**Comment by neauoire** [comment]
Fixed :)
